### PR TITLE
fix: use comm package in backwards compatible way

### PR DESCRIPTION
**Pull request by maartenbreddels**
This makes use of the comm package, but in a backwards compatible way.

Alternative to https://github.com/ipython/comm/pull/6

See 
 * https://github.com/ipython/ipykernel/issues/1026
 * https://github.com/ipython/comm/pull/6

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Not sure I understand what the `ipyparallel` failure is about, and if it is related to this PR?

**Comment by blink1073** [comment]
> Not sure I understand what the ipyparallel failure is about, and if it is related to this PR?

It is not

**Comment by maartenbreddels** [comment]
@martinRenou what's you take on this? Do you think it's preferred over: https://github.com/ipython/comm/pull/6

I don't like the multiple inheritance, but hey, it works.

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by blink1073** [comment]
I'm on holiday, so I'll wait until next Monday to cut a release.

**Comment by martinRenou** [comment]
Thanks a lot @blink1073, and enjoy your holiday ! Sorry for breaking everything right before your holiday 🥲

**Pull request merged**
