### PR TITLE
`_abort_queues` is no longer async

### PR DESCRIPTION
**Pull request by rhelmot**
Resolves some warnings while using qtconsole!

### CODE REVIEW

**Comment by ccordoba12** [comment]
What warnings?

**Comment by rhelmot** [comment]
```
foo
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 foo

NameError: name 'foo' is not defined
/home/audrey/.virtualenvs/angr-c/lib/python3.8/site-packages/ipykernel/kernelbase.py:751: RuntimeWarning: coroutine 'InProcessKernel._abort_queues' was never awaited
  self._abort_queues()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by rayosborn** [comment]
I was about to create an issue on this topic when I noticed this PR. Is there any reason it can't be merged now? I can confirm that the suggested change fixes exception handling in my use of the QtInProcessKernelManager. I think there have been four releases since this was posted.

**Comment by blink1073** [comment]
Sounds reasonable, thanks for the extra confirmation @rayosborn.

**Comment by rayosborn** [comment]
Does anyone know if a new version will be released soon? I am about to release a new version of NeXpy, which currently would have to require ipykernel v6.8.0, but I can hold off for a few days if a release is imminent.

**Comment by blink1073** [comment]
Thanks for the ping @rayosborn, we try not to release on a Friday, but I will make a release on Monday.

**Comment by rayosborn** [comment]
That's great. Thanks.

**Pull request merged**
