### PR TITLE
Release notes for 4.4

### PR DESCRIPTION
**Pull request by minrk**
We should be ready to release 4.4 once #159 and #171 are merged.

### CODE REVIEW

**Comment by takluyver** [comment]
Sorry, this now conflicts because you also added a changelog entry in #159.

Is it also worth mentioning that the `NoOpContext` bug is fixed, by #148?

**Comment by minrk** [comment]
Rebased and added a NoOpContext mention.

**Comment by minrk** [comment]
Thanks! I'll cut the release.

**Comment by minrk** [comment]
4.4 released

**Comment by takluyver** [comment]
Thanks :-)

**Pull request merged**
