### PR TITLE
Automated Changelog Entry for 6.9.2 on main

### PR DESCRIPTION
**Pull request by Carreau**
Automated Changelog Entry for 6.9.2 on main

After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | ipython/ipykernel  |
| Branch  | main  |
| Version Spec | next |
| Since Last Stable | true |

### CODE REVIEW

**Comment by blink1073** [comment]
> could be made a boolean in the form,

That feature isn't available in GitHub yet, everything is a text input

**Comment by Carreau** [comment]
> That feature isn't available in GitHub yet, everything is a text input

I think it has been for a few month:
https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/

**Comment by blink1073** [comment]
Oh nice! I opened https://github.com/jupyter-server/jupyter_releaser/issues/267

**Comment by Carreau** [comment]
Ok, i'll merge this and try to make a release.

**Pull request merged**
