### PR TITLE
Only run Qt eventloop in the shell stream

### LINKED ISSUE #528: Qt slow in Spyder when using ipykernel 5.3.3 (5.3.2 OK)
I am using Spyder 4.1.4 on Miniconda3-py37-4.8.3.
I noticed that matplotlib was unsually slow in IPython when using the Qt backend.
Downgrading ipykernel with conda to version 5.3.0 can however fix the issue.

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #528.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@blink1073, this is my proposed solution for #528. Sorry the delay.

I tested it on my end and found no issues. However, I'll post a message on #528 to see if other users can test it too.

**Comment by blink1073** [comment]
Sounds like we're good, releasing now.

**Comment by blink1073** [comment]
https://pypi.org/project/ipykernel/5.3.4/#files

**Comment by ccordoba12** [comment]
Thanks @blink1073 for releasing a new version with this patch.

**Pull request merged**
