### PR TITLE
appnope segfaults on Apple Silicon

### PR DESCRIPTION
**Pull request by geohot**
I haven't root caused why, but this PR disables it for arm64 chip. Otherwise on M1 the kernels segfault on startup.

### CODE REVIEW

**Comment by mwidjaja1** [comment]
Can confirm, this change fixes Jupyter for me on an ARM Macbook Air!

**Comment by erykoff** [comment]
Note that this solution is just a band-aid on a much deeper wound, see #562 .  Something is not working with ctypes calls on Apple Silicon that is touched by appnope.

**Comment by geohot** [comment]
As far as I can tell, it's just appnope itself that's broken, nothing deeper. Fix here:

https://github.com/minrk/appnope/pull/7

**Comment by mwidjaja1** [comment]
I don't think this change is necessary anymore because as noted in the issue @geohot linked, the issue has been resolved in appnope. I updated appnope today, reverted this MR in my copy of iPython, and I was able to run Jupyterlab natively. 

https://github.com/minrk/appnope/pull/7#issuecomment-735236121

**Comment by geohot** [comment]
Yes, should be good with appnope 0.1.1, which will already be installed. Closing PR.

**Pull request closed without merging**
