### PR TITLE
Revert changes to the Comm Interface

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
@blink1073 what's the issue with the comm this time? do you have a link to an issue?
do the test (your last commit) fail on main now?

**Comment by blink1073** [comment]
https://github.com/ipython/ipykernel/issues/1040#issuecomment-1332040516

**Comment by blink1073** [comment]
The tests pass but the dynamic behavior of widgets wasn't working.

**Comment by blink1073** [comment]
Closing in favor of #1049

**Pull request closed without merging**
