### PR TITLE
Fix Handling of shell.should_run_async

### PR DESCRIPTION
**Pull request by afshin**
Fixes ipython/ipykernel#540

### CODE REVIEW

**Review by blink1073 — COMMENTED** [review]
Thanks!

**Comment by jccurtis** [comment]
Yes thank you! Is there a planned release with this fix?

**Comment by blink1073** [comment]
@meeseeksdev please backport to 5.5.x

**Comment by blink1073** [comment]
Done!  https://pypi.org/project/ipykernel/5.5.1/

**Comment by blink1073** [comment]
I deleted https://pypi.org/project/ipykernel/5.5.1 because we would have to upgrade our ipython dependency to 7.17, which doesn't make sense in a patch release.  cf #607.  This will have to wait for the next minor or major release, whichever comes first.

**Comment by Carreau** [comment]
Noooooooooo. 

That reintroduce the exact bug the change of API was meant to prevent. We have transformers that are stateful; they destroy data if called twice.

`self.shell.transform_cell(code)` should not be called twice in an execution loop. The warning is there for a reason.

**Comment by afshin** [comment]
> That reintroduce the exact bug the change of API was meant to prevent. We have transformers that are stateful; they destroy data if called twice.
> 
> `self.shell.transform_cell(code)` should not be called twice in an execution loop. The warning is there for a reason.

Ah, did we miss passing `transformed_cell` and `preprocessing_exc_tuple` [here](https://github.com/ipython/ipykernel/blob/703510e0fb73dd49edb9154386737c2968d23b6f/ipykernel/ipkernel.py#L316) and perhaps [here](https://github.com/ipython/ipykernel/blob/703510e0fb73dd49edb9154386737c2968d23b6f/ipykernel/ipkernel.py#L331)?

**Pull request merged**
