### PR TITLE
install kernelspec in wheels

### PR DESCRIPTION
**Pull request by minrk**
- wheel kernelspec relies on PATH env to find python, which should be okay when installed to sys.prefix, as opposed to system-wide.
- can't use universal wheels anymore, since Python version is in kernelspec name and display name

It would be ideal to get a hardcoded path at install time (https://github.com/pypa/pip/issues/4032), but for envs this should do until that becomes possible.

After this, it should be a lot harder for the native kernelspec to not be installed, which would be ideal. Plus, uninstalling ipykernel will also uninstall the kernelspec.

### CODE REVIEW

**Comment by takluyver** [comment]
I'm not convinced by relying on PATH - that assumes that people always activate a virtualenv rather than launching scripts inside it directly.

**Comment by minrk** [comment]
We could handle the executable `python` in `jupyter_client` to explicitly mean `sys.executable` (https://github.com/jupyter/jupyter_client/pull/235), which should handle that.

**Comment by minrk** [comment]
Well, crap. I swear I didn't click the merge button, but GitHub interpreted a click in the comment area as a click of the merge button (not sure if it's GitHub's or my browser's fault). I can revert and re-issue the PR if you want, or we can continue to review this PR and I'll open a new one for any changes that should result.

I cleaned up travis.yml a bit to do a 'regular' install rather than an editable one for testing.

**Comment by takluyver** [comment]
Let's carry on without reverting.

**Comment by cben** [comment]
Nice!  It seems this installs the kernel.json `pip install .` but not on `pip install -e .` (which README.md recommends for developement).

**Pull request merged**
