### PR TITLE
Add configure_inline_support and call it in the shell

### PR DESCRIPTION
**Pull request by martinRenou**
This removes a circular dependency between ipykernel and IPython. See https://github.com/ipython/ipython/pull/12814

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
LGTM, thanks!

**Comment by martinRenou** [comment]
Thanks for merging @blink1073 We need to check that this works properly with the current IPython version. I've only tested it coupled with ipython/ipython#12814. Sorry, this should have been a draft PR :S

**Comment by blink1073** [comment]
Thanks for the heads up!  I'll make sure not to cut any releases until then.

**Comment by martinRenou** [comment]
Looks like it works properly 👍🏼 

It will configure the inline backend twice, but I guess we can live with that until IPython removes it.

**Comment by blink1073** [comment]
Great, thanks for following up!

**Pull request merged**
