### PR TITLE
Add content from notebook/pull/124

### PR DESCRIPTION
**Pull request by jdfreder**
sibling PRs:
https://github.com/jupyter/notebook/pull/124

### CODE REVIEW

**Comment by takluyver** [comment]
I'm actually inclined to put the docs for this package in ipython and in jupyter_client, so that there's one less place for documentation to live. The only file there at present is the document on wrapper kernels, and I've already added that [to the jupyter_client docs](http://jupyter-client.readthedocs.org/en/latest/wrapperkernels.html).

**Comment by jdfreder** [comment]
I agree IPython makes sense, but for both.  Why move either of these two (in this PR) to jupyter-client though?

**Comment by takluyver** [comment]
Oh no, these two both belong in IPython. I meant there are some other bits that could conceivably belong here that I'd put in jupyter_client (like the wrapperkernels doc).

**Comment by jdfreder** [comment]
Closing in favor of https://github.com/ipython/ipython/pull/8500

**Pull request closed without merging**
