### PR TITLE
Add release process to CONTRIBUTING.md

### LINKED ISSUE #338: Install broken on 4.9.0 / Python 2
From Python 2 pip:

```
pip install ipykernel
```

This error:

```
Building wheels for collected packages: ipykernel, tornado, scandir
  Running setup.py bdist_wheel for ipykernel ... error
  Complete output from command /Users/brettmz/.virtualenvs/test/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/bg/k1y95mtx0r583fzgqxk6vxy80000gn/T/pip-install-6Gxg_A/ipykernel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/bg/k1y95mtx0r583fzgqxk6vxy80000gn/T/pip-wheel-4unCPn --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/bg/k1y95mtx0r583fzgqxk6vxy80000gn/T/pip-install-6Gxg_A/ipykernel/setup.py", line 91, in <module>
      from ipykernel.kernelspec import write_kernel_spec, make_ipkernel_cmd, KERNEL_NAME
    File "ipykernel/__init__.py", line 2, in <module>
      from .connect import *
    File "ipykernel/connect.py", line 13, in <module>
      from IPython.core.profiledir import ProfileDir
  ImportError: No module named IPython.core.profiledir
```

The installation somehow seems to succeed nevertheless, though the error code does break a few Travis-CI runs - see:

https://travis-ci.org/matthew-brett/nb2plots/builds/422849736

and

https://travis-ci.org/matthew-brett/nb2plots/jobs/422849744

### PR DESCRIPTION
**Pull request by minrk**
- setup.py updated to use setuptools unconditionally (bdist_egg_disabled for disabling implicit eggs)
- setup.py adds setup_requires needed for the kernelspec step when installing from sdist (fixes #338)
- add release process to CONTRIBUTING.md

### CODE REVIEW

**Comment by minrk** [comment]
Finally worked it out. `setup_requires` is dead, long live `pyproject.toml`!

**Comment by ccordoba12** [comment]
> Finally worked it out. setup_requires is dead, long live pyproject.toml

Sorry to chime in here, but just out of curiosity: what pip/setuptools combo does require this?

**Comment by Carreau** [comment]
> Sorry to chime in here, but just out of curiosity: what pip/setuptools combo does require this?

pip 10+ to make full use of the features, but that won't prevent it to work on earlier version IIUC.

**Comment by minrk** [comment]
This is a pretty minor issue, since the only thing that won't work with a too-old version of pip is implicitly pulling in build dependencies when installing from source. If the build dependencies are installed first, lacking this support will have no other consequences.

**Comment by Carreau** [comment]
Ok, let's get that in.

**Pull request merged**
