### PR TITLE
use pss memory info type if available for the resource usage reply

### PR DESCRIPTION
**Pull request by echarles**
Fixes https://github.com/ipython/ipykernel/issues/935

### CODE REVIEW

**Comment by echarles** [comment]
@nishikantparmariam

**Comment by nishikantparmariam** [comment]
This looks good to me.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by blink1073** [comment]
Ah, @echarles this picked up conflicts and needs a `pre-commit` run.

**Comment by blink1073** [comment]
I'll hold off on making the release for now.

**Comment by echarles** [comment]
@blink1073 conflicts are now resolved. I see it is now merged. Thx and happy release :)

**Pull request merged**
