### PR TITLE
Finish 4.7 Change log

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
@Carreau, mind giving this a once-over?

**Comment by minrk** [comment]
@blink1073 I'm going to take a stab at finishing #278 today, which would be nice to get into 4.7, if it can.

**Comment by blink1073** [comment]
Sounds good.

**Comment by blink1073** [comment]
@minrk, we good to go now?

**Comment by blink1073** [comment]
Thanks!  Releasing...

**Pull request merged**
