### PR TITLE
deprecate find_connection_file

### LINKED ISSUE #103: Duplicate function `find_connection_file` with similar API to one in `jupyter_client`
From Gitter [October 21, 2015 5:11 PM](https://gitter.im/jupyter/jupyter?at=5627ff8948fc9e2d6fe877bf):

> So, I was using `find_connection_file` from `jupyter_client.connect`. It turns out there is another implementation under `ipykernel.connect`, which does work. Is there a reason for two different implementations of this function?

Seems like there are two copies of the same function, but they act differently.

If this is intentional, it may be worth finding a different name to highlight the differences and deprecate the old one. If they are meant to behave more similarly, then a bug fix is in order and some discussion should occur about which one to deprecate, if possible, and why.

Related: https://github.com/jupyter/jupyter_client/issues/85

### PR DESCRIPTION
**Pull request by minrk**
It's unused, and the one in jupyter_client should be used instead.

The only case where it might be used is searching for connection files by profile, which no longer makes sense since connection files aren't stored in IPython profiles.

closes #103

### CODE REVIEW

**Comment by minrk** [comment]
Hang on, we use it a little bit internally, but only within the module. A few more deprecations to add...

**Comment by minrk** [comment]
Okay, should be set.

**Comment by takluyver** [comment]
:+1: don't forget to update the changelog.

**Comment by minrk** [comment]
Updated in #106

**Pull request merged**
