### PR TITLE
Deprecate Comm class + Fix incompatibility with ipywidgets (#1097)Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

### PR DESCRIPTION
**Pull request by martinRenou**
cc. @maartenbreddels 

+ fix https://github.com/ipython/ipykernel/issues/1090

### CODE REVIEW

**Comment by martinRenou** [comment]
I disables tests from ipywidgets that are testing deprecation warnings. The remaining test failure on ipywidgets is not due to this PR as it can be replicated in ipywidgets core and should be fixed by https://github.com/jupyter-widgets/ipywidgets/pull/3720

**Comment by martinRenou** [comment]
Friendly ping @blink1073 :D This PR fixes the one remaining issue with the new comm package introduction

**Review by blink1073 — APPROVED** [review]
LGTM, thanks!  I'll cut a release next week.

**Comment by SylvainCorlay** [comment]
Thanks!

**Pull request merged**
