### PR TITLE
Fix: there can be only one comm_manager

### LINKED ISSUE #1043: Latest version break IPyWidgets
IPyKernel Version: 6.18.3
Install Jupyter and ipywidgets 
Run a notebook with the following code
* Cell 1
```python
from ipywidgets import FloatSlider, IntSlider, Image, IntText, link

slider = IntSlider(description="Continuous Slider", continuous_update=True)
textbox = IntText(description="Continuous Text", continuous_update=True)

link((slider, 'value'), (textbox, 'value'))
```
* Cell 2
```
slider
```
* Cell 3
```
textbox
```

Drag the slider and the value in the textbox should change

Now: Install ipykernel==6.17.1 (previous version)
Test the same code and the value in the textbox will end up getting updated.

### PR DESCRIPTION
**Pull request by maartenbreddels**
Fixes #1043

I've tested this branch with our largest ipywidgets based application (yes it was broken before, I confirmed that, a previous test I did was obviously using the wrong environment).
And now it's working well.
@blink1073 shall I put the test of #1048 on top of this?
cc @martinRenou

### CODE REVIEW

**Comment by maartenbreddels** [comment]
FYI, the problem was there every call to `comm.get_comm_manager()` gave a new CommManager, so each widget lived in it's own bubble.

**Comment by blink1073** [comment]
Thanks @maartenbreddels!  Let's try another release...

**Comment by maartenbreddels** [comment]
I’m gonna eat my laptop if the next version needs yanking!

**Comment by blink1073** [comment]
https://github.com/ipython/ipykernel/releases/tag/v6.19.0

**Comment by maartenbreddels** [comment]
image
👀

**Pull request merged**
