### PR TITLE
note deprecations in 4.3 changelog

### PR DESCRIPTION
**Pull request by minrk**
- ipyparallel
- find_connection_file

cc @takluyver

release 4.3 after this?

### CODE REVIEW

**Comment by takluyver** [comment]
It looks like the removal of virtualenv detection (#96) is still in, but not mentioned in the changelog. I'd still prefer not to make that change in 4.x, whether we revert it or do a 4.x branch and backport #105.

**Comment by minrk** [comment]
Yeah, I was going to make the 4.x branch from the parent of that, and backport the few PRs since then.

**Comment by minrk** [comment]
It also depends on whether you want to hold 4.3 for #82, or not.

**Comment by takluyver** [comment]
#82 has been under discussion for long enough that I wouldn't hold 4.3 for it.

Go for it!

**Comment by minrk** [comment]
Released. Will send the appropriate announcements.

**Pull request merged**
