### PR TITLE
use integer counter instead of loop.time() to preserve message ordering

### LINKED ISSUE #356: run all can reorder executions on Windows
https://github.com/jupyter/notebook/issues/4052

### PR DESCRIPTION
**Pull request by minrk**
- avoids need to truncate comparison because it will always be unique
- avoids message reordering issues with low-resolution timers on Windows

closes #356
closes jupyter/notebook#4052
closes ipython/ipython#11348

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks @minrk!

**Comment by PCJimmmy** [comment]
I assume 5.1.0 will be available soon.   The current error all over my scripts - I have to step run thru each very slowly to avoid cells being skipped or the run order wrong.

**Comment by jasongrout** [comment]
5.1.0 was released over a week ago: https://anaconda.org/conda-forge/ipykernel/files for conda, https://pypi.org/project/ipykernel/#history for pypi.

**Comment by esvhd** [comment]
After upgrading to 5.1.0 on Windows I no longer see this issue.

**Comment by PCJimmmy** [comment]
Because of issues with my PC I did a clean windows install on 10/11/2018.  That day or the next (thinking it was the next) I did a full anaconda windows install – 5.0.0 was the version of ipykernel that was installed.  Pretty sure I did a conda update all – so 5.1.0 might not be getting installed.  Not going to do a new clean install to confirm.

Sent from Mail for Windows 10

**Comment by ArthurKhalil** [comment]
"use integer counter instead of loop.time() to preserve message ordering"

What does that even mean? How do i do that? What command do i input in jupyter to do that?

**Pull request merged**
