### PR TITLE
fix and test thread local hook registry

### LINKED ISSUE #180: 'thread._local' object has no attribute 'hooks'
I just installed the newest versions of ipython and GraphLab and noticed this error. Here is the relevant code and the traceback.

    # sales is an SFrame
    graphlab.canvas.set_target('ipynb')
    sales.show(view="Scatter Plot", x="CrimeRate", y="HousePrice")

Traceback:
```


AttributeErrorTraceback (most recent call last)
<ipython-input-7-6f077ba0dabb> in <module>()
      1 graphlab.canvas.set_target('ipynb')
----> 2 sales.show(view="Scatter Plot", x="CrimeRate", y="HousePrice")

/usr/local/lib/python2.7/site-packages/graphlab/data_structures/sframe.pyc in show(self, columns, view, x, y)
   4950             __LOGGER__.warn("Column selection for SFrame.show is deprecated. To show only certain columns, use the sf[['column1', 'column2']] syntax or construct a new SFrame with the desired columns.")
   4951         from ..visualization.show import show
-> 4952         show(self, view=view, x=x, y=y)
   4953 
   4954     def pack_columns(self, columns=None, column_prefix=None, dtype=list,

/usr/local/lib/python2.7/site-packages/multipledispatch/dispatcher.pyc in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/usr/local/lib/python2.7/site-packages/graphlab/canvas/glc_display_dispatch.pyc in show(obj, **kwargs)
      8     import graphlab.canvas.views.sframe
      9     graphlab.canvas.inspect.find_vars(obj)
---> 10     return graphlab.canvas.show(graphlab.canvas.views.sframe.SFrameView(obj, params=kwargs))
     11 
     12 

/usr/local/lib/python2.7/site-packages/graphlab/canvas/utils.pyc in show(variable)
    129         get_target().state.set_selected_variable(variable)
    130         variable.validate_js_component_name(variable.get_js_component())
--> 131     return get_target().show()
    132 
    133 def _get_id(ref):

/usr/local/lib/python2.7/site-packages/graphlab/canvas/target.pyc in show(self, variable)
    175             IPython.core.display.Javascript(
    176                 data=self.__makeJS(_to_json(data), view.get_js_file(), view.get_js_component()),
--> 177                 css=['//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css', self.get_asset_url() + 'css/canvas.css']
    178             )
    179         )

/usr/local/lib/python2.7/site-packages/IPython/core/display.pyc in display_javascript(*objs, **kwargs)
    328         Metadata to be associated with the specific mimetype output.
    329     """
--> 330     _display_mimetype('application/javascript', objs, **kwargs)
    331 
    332 

/usr/local/lib/python2.7/site-packages/IPython/core/display.pyc in _display_mimetype(mimetype, objs, raw, metadata)
     74         # turn list of pngdata into list of { 'image/png': pngdata }
     75         objs = [ {mimetype: obj} for obj in objs ]
---> 76     display(*objs, raw=raw, metadata=metadata, include=[mimetype])
     77 
     78 #-----------------------------------------------------------------------------

/usr/local/lib/python2.7/site-packages/IPython/core/display.pyc in display(*objs, **kwargs)
    169                 # kwarg-specified metadata gets precedence
    170                 _merge(md_dict, metadata)
--> 171             publish_display_data(data=format_dict, metadata=md_dict)
    172 
    173 

/usr/local/lib/python2.7/site-packages/IPython/core/display.pyc in publish_display_data(data, metadata, source)
    119     InteractiveShell.instance().display_pub.publish(
    120         data=data,
--> 121         metadata=metadata,
    122     )
    123 

/usr/local/lib/python2.7/site-packages/ipykernel/zmqshell.pyc in publish(self, data, metadata, source)
    109         # message or None. If None is returned,
    110         # the message has been 'used' and we return.
--> 111         for hook in self.thread_local.hooks:
    112             msg = hook(msg)
    113             if msg is None:

AttributeError: 'thread._local' object has no attribute 'hooks'
```

### PR DESCRIPTION
**Pull request by minrk**
only the main thread initialized hooks correctly, so other threads would see AttributeError('hooks') on other threads.

closes #180

### CODE REVIEW

**Comment by takluyver** [comment]
Nothing obviously wrong, but I haven't followed this bit of the code closely enough to know exactly how/why we're using thread local data. Do you think it needs more careful review, or are you confident in it?

**Comment by minrk** [comment]
It's straightforward and test covers it, so I'm pretty confident.

**Comment by minrk** [comment]
@takluyver thanks! I'll make a release shortly. Since a few 4.5 PRs [have been merged](https://github.com/ipython/ipykernel/milestone/14?closed=1), do you have an opinion on making a backport 4.4.2 release stripping these out, or just releasing 4.5? I'll update the milestones to match whatever we end up doing. I'm leaning slightly towards just releasing 4.5, and bumping the remaining [issue](https://github.com/ipython/ipykernel/milestone/14) to 4.6.

**Comment by takluyver** [comment]
I'm fine with making a 4.5 release; it's not really any more effort than doing 4.4.2, is it? Release early, release often, and all that jazz.

**Comment by minrk** [comment]
Indeed. I'll do 4.5, then.

**Comment by minrk** [comment]
@takluyver 4.5 changelog in #189, then I'll release.

**Pull request merged**
