### PR TITLE
Configurables needs to be configurable

### PR DESCRIPTION
**Pull request by Carreau**
IPython rely on configurables being configurables to ... configure things.

Comm seem to insert or return a non-configurable in IPython, that make ipykernel crash in some instances. For example but not limited to:

    %config Completer.use_jedi = False

Or trying to use hvplot for example.

This is just a "this is wrong" PR, there should be a proper fix, and I will likely add a hard check in IPython that what is added in configurables is actually a configurables.

This will need a fix in a Comm pacakge.

### CODE REVIEW

**Comment by Carreau** [comment]
cc @fperez

**Comment by blink1073** [comment]
Thanks for the report!  I'll make a new release with this tomorrow.

**Comment by fperez** [comment]
Thx a lot @blink1073!! 

cc @yuvipanda @tsnow03 @weiji14 - we might be able to release the ipykernel pin on our cryo env soon.

**Comment by blink1073** [comment]
I already yanked the offending version, you should be able to remove the pin now

**Comment by fperez** [comment]
Ah, got it, thx!

**Comment by weiji14** [comment]
Looks like [`ipykernel=6.18.1` on conda-forge](https://anaconda.org/conda-forge/ipykernel/files?version=6.18.1) isn't marked as broken yet, so maybe keep the pin around for a little longer :slightly_smiling_face:

**Comment by blink1073** [comment]
https://github.com/ipython/ipykernel/releases/tag/v6.18.2

**Pull request merged**
