### PR TITLE
Removed filtering of stack frames for testing

### LINKED ISSUE #629: IPykernel Debugger
Hi,

I tried `6.0.0a2` and found that while I could add breakpoints, variables did not appear.

image

The server has the following error:
```
Traceback (most recent call last):
  File "/path/to/myvenv/lib64/python3.7/site-packages/ipykernel/debugger.py", line 327, in stackTrace
    module_idx = len(sf_list) - next(i for i, v in enumerate(reversed(sf_list), 1) if v['name'] == '<module>' and i != 1)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/myvenv/lib64/python3.7/site-packages/ipykernel/kernelbase.py", line 217, in process_control
    yield gen.maybe_future(handler(self.control_stream, idents, msg))
  File "/path/to/myvenv/lib64/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/path/to/myvenv/lib64/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/path/to/myvenv/lib64/python3.7/site-packages/ipykernel/kernelbase.py", line 729, in debug_request
    reply_content = yield gen.maybe_future(self.do_debug_request(content))
  File "/path/to/myvenv/lib64/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/path/to/myvenv/lib64/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/path/to/myvenv/lib64/python3.7/site-packages/ipykernel/ipkernel.py", line 410, in do_debug_request
    return (yield self.debugger.process_request(msg))
  File "/path/to/myvenv/lib64/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/path/to/myvenv/lib64/python3.7/site-packages/ipykernel/debugger.py", line 455, in process_request
    reply = await handler(message)
RuntimeError: coroutine raised StopIteration
```

### PR DESCRIPTION
**Pull request by JohanMabille**
Fixes #629 

@mlucool can you confirm?

### CODE REVIEW

**Comment by mlucool** [comment]
This works for me - thanks! Will you release a new alpha after as well?

**Comment by JohanMabille** [comment]
I don't have the permission for that, but I'm sure we can ask @blink1073 ;) But I need to understand the failure before (although it looks totally unrelated).

**Comment by JohanMabille** [comment]
According to @davidbrochart, the failures are due to the last release of Jupyter Client:

> for instance get_msg() doesn't have a block kwargs anymore

David is working on a PR to fix the tests, I will rebase when it is merged.

**Comment by SylvainCorlay** [comment]
Let's tag a release.

**Comment by SylvainCorlay** [comment]
6.0.0a3 is out with that fix.

**Pull request merged**
