### PR TITLE
Add changelog for 5.1.2

### PR DESCRIPTION
**Pull request by willingc**
Addresses #420

### CODE REVIEW

**Comment by blink1073** [comment]
https://github.com/ipython/ipykernel/releases/tag/v5.1.2

**Comment by Carreau** [comment]
Thanks @blink1073 !

As a side note, can we try to keep the consistency in repositories, with the naming of tags, and wether or not there  are keeping a leading `v` or not ? 

We could also add 2 tag with and w/o `v`, but think it would be better if same repo keep same format.

**Comment by blink1073** [comment]
Agreed, the leading "v" is an artifact of my bash function for making python releases. Happy to standardize one way or the other.

**Comment by Carreau** [comment]
> Agreed, the leading "v" is an artifact of my bash function for making python releases. Happy to standardize one way or the other.

Also now PyPI support upload tokens (still beta-ish), so we can try to go release via travis /azure/whatever.

Probably just a question of figuring out if it's a tagged version I guess.

**Comment by blink1073** [comment]
A leading "v" would help with that. ;)

cf https://github.com/jupyterlab/jupyterlab/issues/6819
cf https://github.com/jupyterlab/jupyterlab/pull/6534

**Pull request merged**
