### PR TITLE
Use traitlets 4.1 .tag() for config metadata

### PR DESCRIPTION
**Pull request by jasongrout**
This depends on https://github.com/ipython/traitlets/pull/53, which was included in traitlets 4.1.0.

### CODE REVIEW

**Comment by jasongrout** [comment]
@minrk, @SylvainCorlay - I think this ready for review now.

**Comment by SylvainCorlay** [comment]
@Carreau?

**Comment by Carreau** [comment]
> @Carreau?

Cf comment on https://github.com/jupyter/nbformat/pull/14 , and on Jupyter Hackpad. 

I'm cleaning the PR list, and this is stalling because we need to decide on 4.1 as a deps explicitly and move forward once and for all instead of having Jason rebasing 12 PRs every couple of weeks.
At least me closing can allow you to complain tomorrow at the meeting and get a decision on which we can move forward.

**Comment by Carreau** [comment]
Ok, one PR at a time. Reopening this one. 
Lets get this in, add test on CI that prevent using older syntax, and do the same on another repo.

**Comment by takluyver** [comment]
I don't think we really need to create tests for this. There are visible warnings if something uses the old style, that should be fine.

**Comment by Carreau** [comment]
Ok, last read of that and merging.

**Comment by Carreau** [comment]
Thanks @jasongrout !

**Comment by SylvainCorlay** [comment]
:+1:

**Pull request merged**
