### PR TITLE
Test downstream projects

### PR DESCRIPTION
**Pull request by davidbrochart**
It looks like ipykernel master breaks nbclient. I reproduced locally and I can see messages like:
```python
msg = {"shell": {...}, "control": {}}
```
where `...` is a regular message (with its `header` and so on).
Any idea where this could come from?

### CODE REVIEW

**Comment by davidbrochart** [comment]
I think it comes from here:
https://github.com/ipython/ipykernel/blob/5d21c8f9c2fd4d4e049e73fa6e2664c6a32870c7/ipykernel/comm/comm.py#L69
I don't know ipykernel, but it looks like we should choose a channel here, e.g.:
```python
parent=self.kernel._parent_header["shell"]
```

**Comment by davidbrochart** [comment]
The last commit seems to fix this issue, but now there are other errors:
```
At index 0 diff:
{'ename': 'KeyboardInterrupt', 'evalue': '', 'output_type': 'error', 'traceback': ['---------------------------------------------------------------------------', 'KeyboardInterrupt                         Traceback (most recent call last)', '<IPY-INPUT> in <module>\n----> 1 while True: continue\n', 'KeyboardInterrupt: ']} !=
{'output_type': 'error', 'ename': 'KeyboardInterrupt', 'evalue': '', 'traceback': ['---------------------------------------------------------------------------', 'KeyboardInterrupt                         Traceback (most recent call last)', '/tmp/ipykernel_1789/2216019953.py in <module>\n----> 1 while True: continue\n', 'KeyboardInterrupt: ']}
```
It looks like the cell "file name" changed, and that is reflected in the traceback.
Is it related to the work done on the debugger?

**Comment by davidbrochart** [comment]
Regarding this error:
```
E         + [IPKernelApp] ERROR | Invalid Control Message
E         + Traceback (most recent call last):
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 198, in process_control
E         +     msg = self.session.deserialize(msg, content=True, copy=False)
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/jupyter_client/session.py", line 917, in deserialize
E         +     msg_list[i] = msg_list[i].bytes
E         + IndexError: list index out of range
E         + ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f2ce71d37c0>>, <Future finished exception=ValueError('DELIM not in msg_list')>)
E         + Traceback (most recent call last):
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
E         +     ret = callback()
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
E         +     future.result()
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
E         +     yielded = self.gen.throw(*exc_info)  # type: ignore
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 191, in poll_control_queue
E         +     yield self.process_control(msg)
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
E         +     value = future.result()
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
E         +     yielded = ctx_run(next, result)
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 196, in process_control
E         +     idents, msg = self.session.feed_identities(msg, copy=False)
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/jupyter_client/session.py", line 859, in feed_identities
E         +     raise ValueError("DELIM not in msg_list")
E         + ValueError: DELIM not in msg_list
```
I cannot reproduce locally. I'm going to try and debug in the CI.

**Comment by SylvainCorlay** [comment]
Release 6.0.0a4 with the latest fixes. It may be interesting to rebase this on master.

**Comment by davidbrochart** [comment]
Except for some assertions that we have to soften in nbclient, there is this error:
```
E       assert 'ERROR:tornad... non-socket\n' == ''
E         + ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f532d2adf40>>, <Future finished exception=ZMQError('Socket operation on non-socket')>)
E         + Traceback (most recent call last):
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
E         +     ret = callback()
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
E         +     future.result()
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/tornado/gen.py", line 775, in run
E         +     yielded = self.gen.send(value)
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 416, in dispatch_queue
E         +     self.control_stream.flush()
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 354, in flush
E         +     self._handle_recv()
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 470, in _handle_recv
E         +     msg = self.socket.recv_multipart(zmq.NOBLOCK, copy=self._recv_copy)
E         +   File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/zmq/sugar/socket.py", line 583, in recv_multipart
E         +     parts = [self.recv(flags, copy=copy, track=track)]
E         +   File "zmq/backend/cython/socket.pyx", line 781, in zmq.backend.cython.socket.Socket.recv
E         +   File "zmq/backend/cython/socket.pyx", line 814, in zmq.backend.cython.socket.Socket.recv
E         +   File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
E         + zmq.error.ZMQError: Socket operation on non-socket
```

**Comment by SylvainCorlay** [comment]
The notebook output errors are expected changes due to the debugger support, which makes the traceback message a little bit different wrt filenames.

**Comment by davidbrochart** [comment]
> These are expected changes due to the debugger support, which makes the traceback message a little bit different wrt filenames.

It would be good to support passing a path, e.g. `path_to_my_cell_dir` instead of having e.g. `/tmp/ipykernel_647963/156288784.py` that is kind of random. The `path_to_my_cell_dir` directory could be populated with incrementing file names for example, like `1.py`, `2.py`, etc. That would make testing easier.

**Comment by SylvainCorlay** [comment]
Indeed there are some test failures in ipyparallel. I don't know if these failures already occur with ipykernel stable.

cc @minrk

**Comment by davidbrochart** [comment]
I just tested ipykernel master with nbclient, and there are `zmq.error.ZMQError: Socket operation on non-socket` errors (see https://github.com/jupyter/nbclient/pull/146/checks?check_run_id=2450827376):
```
  E         + ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7fc058f7fe50>)
  E         + Traceback (most recent call last):
  E         +   File "/home/runner/work/nbclient/nbclient/.tox/py38/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
  E         +     ret = callback()
  E         +   File "/home/runner/work/nbclient/nbclient/.tox/py38/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 535, in <lambda>
  E         +     self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  E         +   File "/home/runner/work/nbclient/nbclient/.tox/py38/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 447, in _handle_events
  E         +     zmq_events = self.socket.EVENTS
  E         +   File "/home/runner/work/nbclient/nbclient/.tox/py38/lib/python3.8/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
  E         +     return self._get_attr_opt(upper_key, opt)
  E         +   File "/home/runner/work/nbclient/nbclient/.tox/py38/lib/python3.8/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
  E         +     return self.get(opt)
  E         +   File "zmq/backend/cython/socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  E         +   File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
  E         + zmq.error.ZMQError: Socket operation on non-socket
```

**Comment by SylvainCorlay** [comment]
Rebased on 6.0.0a6.

**Comment by minrk** [comment]
For ipyparallel, can you test `main`? I've fixed a few things since the last alpha, but probably won't be able to make a release for some weeks. I might be able to make a quick prerelease, if that's easier.

I think I recall seeing a parent-header-related issue when I had master of ipykernel installed locally, relating to parent headers and the output widget, I believe. Not sure if that would be covered by widgets tests

**Comment by SylvainCorlay** [comment]
Now testing `ipyparallel@main`.

We are seeing the same failure as previously, with `AssertionError: TaskAborted not raised by get`.

**Comment by JohanMabille** [comment]
> /tmp/ipykernel_647963/156288784.py that is kind of random

This is not random at all, the pattern is `/tmp/ipykrnel_{pid}/{murmurhash(cell_content)}.py`

**Comment by minrk** [comment]
I've tracked down the abort test to the fact that the debugger is not enabled and the control thread is not running in ipyparallel, which is the default behavior of the Kernel object. The result is that control thread priority is not preserved, and the shell channel can now starve the control channel (rather than the other way around, which is the prior and correct behavior). I think this is an issue, and just need to consider options:

1. fix control channel priority when control thread is not running (most compatible, probably most complicated)
2. *require* control thread for control channel priority behavior (and launch control thread in IPP). Most backward-incompatible, but simplest.
    a. less backward-incompatible is to make instantiating a control thread the default behavior in Kernel itself, rather than KernelApp

I'll try to figure out what's involved in each and what makes the most sense. I'm guessing for maintenance purposes, ensuring the control thread is running might actually be the simplest way to go since there won't be two different ways for control and shell queues to interact.

**Comment by SylvainCorlay** [comment]
green

**Comment by davidbrochart** [comment]
Future jupyter_client v7 works, that's great!

**Comment by davidbrochart** [comment]
We have this error in nbclient's tests:
```
E         + Traceback (most recent call last):
E         +   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
E         +     return _run_code(code, main_globals, None,
E         +   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/runpy.py", line 87, in _run_code
E         +     exec(code, run_globals)
E         +   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/ipykernel_launcher.py", line 16, in <module>
E         +     app.launch_new_instance()
E         +   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/traitlets/config/application.py", line 844, in launch_instance
E         +     app.initialize(argv)
E         +   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/traitlets/config/application.py", line 87, in inner
E         +     return method(app, *args, **kwargs)
E         +   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 616, in initialize
E         +     self.init_sockets()
E         +   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 281, in init_sockets
E         +     self.stdin_port = self._bind_socket(self.stdin_socket, self.stdin_port)
E         +   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 223, in _bind_socket
E         +     return self._try_bind_socket(s, port)
E         +   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 199, in _try_bind_socket
E         +     s.bind("tcp://%s:%i" % (self.ip, port))
E         +   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/zmq/sugar/socket.py", line 172, in bind
E         +     super().bind(addr)
E         +   File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
E         +   File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
E         + zmq.error.ZMQError: Address already in use
```

**Comment by SylvainCorlay** [comment]
Not sure if we should keep the `IPYKERNEL_CELL_NAME`.

**Comment by SylvainCorlay** [comment]
So it seems that

 - downstream tests with the main branch of `jupyter_client` pass but not with the latest release.
 - the main branch of `jupyter_client` breaks `nbclient`.

**Comment by SylvainCorlay** [comment]
OK, so I don't see any blocker for moving forward with the ipykernel changes at least. That is great news!

**Comment by kevin-bates** [comment]
Thanks for the ping.  I suspect I'm not looking at the correct thing because [this](https://github.com/ipython/ipykernel/pull/635/checks?check_run_id=2531327770#step:5:33) is the only error(s) I see in the downstream test, which is due to the fact that we've removed the deprecated `cleanup()` method and should be replaced with `cleanup_resources()`.

**Comment by davidbrochart** [comment]
Sorry for not clarifying, this is the log: https://github.com/ipython/ipykernel/runs/2530626417

**Comment by kevin-bates** [comment]
Thanks David.  This looks a little odd: https://github.com/ipython/ipykernel/runs/2530626417#step:5:173, especially since I thought the workflow was installing the `[test]` extras from jupyter_client - which includes `pytest-asyncio`.  IIRC, using `pytest-asyncio` helped quite a lot - perhaps that might help here.

**Comment by davidbrochart** [comment]
Yes, I was thinking the same, but jupyter-client 6.1.12 had [`pytest-asyncio` already](https://github.com/jupyter/jupyter_client/blob/6b1aa1cdd39daea559966da75f265ed7a8998602/setup.py#L86), so I don't understand.

**Comment by davidbrochart** [comment]
I can try, thanks.

**Comment by davidbrochart** [comment]
Although, `pytest-asyncio` has [already installed](https://github.com/ipython/ipykernel/runs/2530626417#step:4:381).

**Comment by ccordoba12** [comment]
Could you wait for us to run our test suite with the ipykernel master? I could have an answer for you tomorrow.

Also, does that require the latest jupyter_client?

**Comment by davidbrochart** [comment]
Sure @ccordoba12 we can wait for you to run your test suite.
ipykernel master shouldn't require jupyter-client master, but we are seeing that some tests fail with the latest release of jupyter-client, although it's almost a test setup issue.

**Comment by SylvainCorlay** [comment]
@ccordoba12 we have been tagging pre-releases of ipykernel 6.0 for some time. Don't hesitate to try out the latest with Spyder!

**Comment by ccordoba12** [comment]
Great, thanks! I'll report back after running our tests in both our kernel and main repos.

**Comment by davidbrochart** [comment]
Hi @ccordoba12, did you get a chance to test ipykernel master?

**Comment by blink1073** [comment]
Kicking CI

**Comment by blink1073** [comment]
This is passing now, ready for review?

**Comment by davidbrochart** [comment]
I'm not sure we want to test ipykernel master with downstream packages' master, otherwise it might fail quite often.
Isn't the goal to test ipykernel master with downsteam packages' releases?

**Comment by SylvainCorlay** [comment]
I am in favor of merging this - even with an allow-failure tag, so that we are aware of unintentional breakage in ipykernel's API.

@davidbrochart Do you know the reason for the remaining failure?

**Comment by davidbrochart** [comment]
The remaining failures are in ipyparallel: `fixture 'io_loop' not found`.

**Comment by davidbrochart** [comment]
I think this is not ready to be (squashed and) merged.

**Review by blink1073 — APPROVED** [review]
Excellent, thank you!

**Pull request merged**
