### PR TITLE
Adding proper activation for conda envs to ipykernel creation

### LINKED ISSUE #416: Interest in adding support for in-notebook conda commands?
Hi ipykernel team! When using a Jupyter notebook with a conda environment, `!conda` commands do not operate on the conda environment that the user's kernel is running in. At least, not without some surgery to the kernel.json file. 

Below, I motivate the use-case for why you want to properly activate a conda environment before launching a kernel out of it. **Is there interest from the ipykernel team in accepting a pull-request that adds this functionality to the `install` subcommand on ipykernel?** 

First pass at a proposed API is to add a `--conda` flag to the call so that it would look like `python -m ipykernel install --user --name <kernel name> --conda`. But, before any work is done to add this to the ipykernel code base, let's discuss in an issue.

## Motivating the problem

@parente and I found that it was a pretty common user expectation that they could add a package to their environment when running in a jupyter notebook by executing `!conda install <whatever package>`. As such, we (actually mostly @parente) ended up writing [kernda](https://github.com/Valassis-Digital-Media/kernda) so we could add `source activate <conda env>` to the launch script in the kernel.json file in a reliable way.

The usage is as follows:
1. create your conda environment: `conda create -n moviepy moviepy ipykernel -c conda-forge`
2. activate it and create your kernel: `conda activate moviepy`, `python -m ipykernel install --user --name moviepy`

At this point, let's inspect the kernel.json file:
```json
{
 "argv": [
  "/home/ericdill/miniconda/envs/moviepy/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "moviepy",
 "language": "python"
}
```

This kernel will successfully launch a kernel out of the `moviepy` conda environment, but it notably is not _activating_ the environment. This has two main ramifications:
1. There are scripts in ./activate.d/ and ./deactivate.d/ that, most commonly, set and unset environmental variables that can be required for proper conda behavior. I'll track down a few of these packages to provide some concrete examples
2. There can be a user expectation that `!conda` operates on the conda environment that the kernel is running out of.

So, let's use kernda to edit this kernel.json file to add `source activate` to the script:

```
conda install kernda -c conda-forge
kernda --display-name 'moviepy [py37]' /home/ericdill/.local/share/jupyter/kernels/moviepy/kernel.json
```

This will output the following that you can either redirect into the proper file (or you can use the `-i` flag to overwrite the original):
```
{
  "argv": [
    "bash",
    "-c",
    "source \"/home/ericdill/miniconda/bin/activate\" \"/home/ericdill/miniconda/envs/moviepy\" && exec /home/ericdill/miniconda/envs/moviepy/bin/python -m ipykernel_launcher -f '{connection_file}' "
  ],
  "display_name": "moviepy [py37]",
  "language": "python"
}
```

At this point we will have a kernel that has proper conda activation and gives the user the `!conda` functionality in their notebook.

### PR DESCRIPTION
**Pull request by ericdill**
Discussion and details in #416 

Closes #416 

What are your general thoughts so far @blink1073? I could use some help thinking through how this should be tested.

TODO:
* [ ] establish best way to test this. I'm definitely open to suggestions. My idea is to create a conda environment including ipykernel, create a kernel with this new code path and make sure that the kernel can start. That seems like a very slow test though, so... thoughts?
* [ ] QA on windows. I'll be able to do soon.
* [ ] this will require conda 4.6 as a minimum version. From a UX perspective, it would be a good idea to put some safeguards in place to ensure that the user's environment _supports_ `conda run` by checking the conda version during kernel install.

Notes

* This implementation assumes that the process that is launching your kernels knows how to handle the `conda run` command -- in other words the notebook / lab environment that is spawning kernels should have been installed with conda too.

### CODE REVIEW

**Comment by ericdill** [comment]
Build failure is for 3.7-dev and seems unrelated

**Comment by blink1073** [comment]
I think we should test the version of conda using LooseVersion and error out on the CLI.  I think having a separate CI build for the conda envy testing is fair.

**Comment by blink1073** [comment]
We could check the location of the “jupyter” executable using shutil.which and see if it matches the conda location.

**Comment by ericdill** [comment]
Just tried this on windows and got the following error. I suspect that I need to handle `conda` differently.

```
[E 21:58:59.780 NotebookApp] Failed to run command:
    ['conda', 'run', '-n', 'envs', 'python', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\Eric\\AppData\\Roaming\\jupyter\\runtime\\kernel-66d6318b-d76e-4269-b036-0d26a4dfcb79.json']
        PATH='C:\\Users\\Eric\\AppData\\Local\\Continuum\\miniconda3\\envs\\ipykernel-dev;C:\\Users\\Eric\\AppData\\Local\\Continuum\\miniconda3\\envs\\ipykernel-dev\\Library\\mingw-w64\\bin;C:\\Users\\Eric\\AppData\\Local\\Continuum\\miniconda3\\envs\\ipykernel-dev\\Library\\usr\\bin;C:\\Users\\Eric\\AppData\\Local\\Continuum\\miniconda3\\envs\\ipykernel-dev\\Library\\bin;C:\\Users\\Eric\\AppData\\Local\\Continuum\\miniconda3\\envs\\ipykernel-dev\\Scripts;C:\\Users\\Eric\\AppData\\Local\\Continuum\\miniconda3\\envs\\ipykernel-dev\\bin;C:\\Users\\Eric\\AppData\\Local\\Continuum\\miniconda3\\condabin;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0;C:\\windows\\System32\\OpenSSH;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Users\\Eric\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Eric\\AppData\\Local\\inkdrop\\bin;C:\\Users\\Eric\\AppData\\Local\\GitHubDesktop\\bin'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': 'C:\\Users\\Eric\\Documents\\GitHub\\ipykernel', 'close_fds': False}

[E 21:58:59.780 NotebookApp] Uncaught exception POST /api/sessions (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
        type=mtype))
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\tornado\gen.py", line 209, in wrapper
        yielded = next(result)
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
        **kw)
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "C:\Users\Eric\AppData\Local\Continuum\miniconda3\envs\ipykernel-dev\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[W 21:58:59.845 NotebookApp] Unhandled error
[E 21:58:59.846 NotebookApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "X-Xsrftoken": "2|3cf61930|d5bec6b8e0aaf72a225eb2598c5de8b7|1574650588",
      "X-Requested-With": "XMLHttpRequest",
      "Content-Length": "97",
      "Origin": "http://localhost:8888",
      "Dnt": "1",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=ipykernel-dev",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1574650732|23:username-localhost-8888|44:NTc1MjYwODdhODQzNDI2MGEyOTJiMDA4MzEyOGVlN2Y=|f97b0b88fcfdf9c7fc1828ed71ca9f448699db636505d66df40a8c25693024e3\"; _xsrf=2|3cf61930|d5bec6b8e0aaf72a225eb2598c5de8b7|1574650588"
    }
[E 21:58:59.846 NotebookApp] 500 POST /api/sessions (127.0.0.1) 151.14ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=ipykernel-dev
[I 21:59:09.092 NotebookApp] Saving file at /Untitled.ipynb
```

**Pull request closed without merging**
