### PR TITLE
Update Pytest configuration (deprecated implicit asyncio mode)

### PR DESCRIPTION
**Pull request by Carreau**
This make downstream test fail.

### CODE REVIEW

**Comment by Carreau** [comment]
Ok, I'm confused why downstream it asks for the option and here it says the option is unknown

**Comment by blink1073** [comment]
If you're referring to `IPython`'s downstream checks, I think the check is using the `pytest` config from `IPython` itself.  In the `downstream-test` action in `jupyterlab/maintainer-tools` we made sure to put the downstream folder in a separate file hierarchy to avoid this.

**Comment by Carreau** [comment]
Thanks for the pointers I'll try to have a look.

**Comment by Carreau** [comment]
Thanks for the pointers I'll try to have a look.

**Pull request closed without merging**
