### PR TITLE
Check for number types using the python type hierarchy

### PR DESCRIPTION
**Pull request by jasongrout**
This lets numpy numeric types to work with json cleaning functions, for example.

CC @ChakriCherukuri

### CODE REVIEW

**Comment by jasongrout** [comment]
I'm not sure how the test that had `Int(5)` worked, since it gave errors because Int wasn't defined...

**Comment by minrk** [comment]
Thanks!

**Comment by jasongrout** [comment]
@minrk - This is biting us.  It would be awesome if we could do a small patch release with this patch.  How much effort is it to do a patch release?

**Comment by SylvainCorlay** [comment]
@jasongrout thanks for fixing this. I am :+1: for a patch release.

**Comment by minrk** [comment]
Not much. There's another patch we want to get in, then we can cut a release.

**Comment by minrk** [comment]
@jasongrout released 4.2.2 with this.

**Pull request merged**
